### ISSUE TITLE
Sender and Traveller: sign up for / log into the app

### ISSUE THREAD

**Issue by minaorangina** [ayooo-team/prototype#18]
As a user, I want to be able to log into or sign up securely to use Ayooo's services. I want to be able to sign up or log in through this page.
##### This page will display:
- [x] Form requesting email address and password #1 
#### Functionality to include:
- [x] Determine if user is already logged in, ~~by checking cookie~~ with Local Storage (using Firebase)
- [ ] if user has already logged in, authentication is bypassed --> to Dashboard view
- [x] Determine if user is a new user, or a returning customer.
- [x] New users will be saved in Firebase and assigned a unique ID
- [x] Returning users' details will be retrieved from firebase, using the email to match them in the database
- [ ] Implement cookie after login for users without cookie

**Comment by mk4111** [comment]
@minaorangina could we also please include the following:
- "store a user's 'loggedin' status in a cookie"
- "check cookie on page load"
- "if cookie exists, reroute them to "Dashboard" page"

Thank you!

**Comment by mk4111** [comment]
Completed in pull-request #27
