### ISSUE TITLE
'Client': (MATCHING) see who wants to send a package

### ISSUE THREAD

**Issue by minaorangina** [ayooo-team/prototype#19]
#### As the client, I want to see who wants to send a package with Ayooo

N.B. Client to check the Ayooo spreadsheet

Contents of spreadsheet: 
- [ ] Sender's email address
- [ ] Sender parcel details
- [ ] date for parcel to be sent
- [ ] Sender's proposed price

This will enable the Client to match customers up

**Comment by mk4111** [comment]
@minaorangina I think there's been a little bit of miscommunication. Given that we agreed to continue with our original scope of work in our meeting with Dan (held 24/03/2016), we will not be using Mandrill to automate emails.

**Comment by minaorangina** [comment]
have now updated the checklist above
