### ISSUE TITLE
Wireframes

### ISSUE THREAD

**Issue by minaorangina** [ayooo-team/prototype#28]
@PAOLOPRIAMODAMU can you please put the app wireframes you showed us last week in the shared assets folder?  Thanks!

**Comment by PAOLOPRIAMODAMU** [comment]
I can't because it is in protoio software. I gave you the access details

On Wednesday, 30 March 2016, Mina notifications@github.com wrote:

> @PAOLOPRIAMODAMU https://github.com/PAOLOPRIAMODAMU can you please put
> your app wireframes in the assets folder please? Thanks!
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/ayooo-team/prototype/issues/28

## 

Inviato da Gmail Mobile

**Comment by mk4111** [comment]
Hi @PAOLOPRIAMODAMU I don't think we have been given the access details. 
We have received the domain details - is the username and password the same for both?

**Comment by PAOLOPRIAMODAMU** [comment]
Email: paolodamu@gmail.com
Password: PD1990dp?
Username: choose the one on the middle

Thanks
Paolo

On Wednesday, 30 March 2016, Marie <notifications@github.com> wrote:

> Hi @PAOLOPRIAMODAMU <https://github.com/PAOLOPRIAMODAMU> I don't think we
> have been given the access details.
> We have received the domain details - is the username and password the
> same for both?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ayooo-team/prototype/issues/28#issuecomment-203442795>
>


-- 
Inviato da Gmail Mobile

**Comment by iteles** [comment]
@mk4111 @minaorangina Please take not of the above details into your shared google doc (with other user details) and delete the comment from github :+1:

**Comment by mk4111** [comment]
@iteles, done!

**Comment by mk4111** [comment]
@PAOLOPRIAMODAMU as mentioned before, please refrain from posting any user details onto Github as this is publicly accessible! If you could email them to us from next time onwards, we would be most grateful! Thank you
