### ISSUE TITLE
'Sender': I want to make a request for someone to deliver my package.

### ISSUE THREAD

**Issue by mk4111** [ayooo-team/prototype#5]
As a user, I want to post a request online. If anyone who is en-route to that destination sees my post, they will be able to contact me.
- [ ] Display sender name
- [ ] Display package details - weight, size, destination, date
- [ ] An input box for the price of delivery
- [ ] A button for travellers (interested in delivering) to click

---
- [ ] Clicked button will send an email confirmation of 'interest shown' to both clickee and the Client. The Client will then be able to notify both the 'Sender' and potential 'Traveller' manually.

**Comment by iteles** [comment]
Have you finalised the scope of the MVP with Paolo? There was talk for a while of not having this portion and replacing it with having just a list of possible couriers and the sender would have to go through the list and pick the one they were interested in. This would remove the need for Paolo to manually match senders and couriers. Worth checking!

**Comment by minaorangina** [comment]
As of meeting on 24/03, this has now changed to:

#### As a Sender, I want to request for my parcel to be picked up and delivered to my destination. Ayooo will take it from there.

**input package details**
- [ ] fields for weight, size, destination and date
- [ ] fields to determine price sender wants to pay
- [ ] A notification that Ayooo will take it from there.
